project:
  type: website

website:
  reader-mode: true
  favicon: logo.png
  title: "SpatFD"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: intro_spatial.qmd
        text: Cuadernos de Estadística Espacial
      - section: "Geoestadística"
        contents:
          - href: GeoestadísticaConSgeostat.qmd
            text: Geoestadística con Sgeostat
          - href: GeoestadisticaUnivariadaConGeoR.qmd
            text: Geoestadística Univariada con GeoR
          - href: Kriging_puntual.qmd
            text: Kriging
      - section: "Modelos de Regresión Espacial"
        # contents:
        #  - href: modelos_regresion.qmd
          #  text: Modelos de Regresión Espacial
          # - href: leukemia.qmd
          #   text: Modelado Espaciald de Leucemia
      - section: "Estadística Espacial Funcional"
        contents:
          - href: index.qmd
            text: Home
          - href: about.qmd
            text: About
      - section: "Objetos"
        contents:
          - href: spatfd_object.qmd
            text: SpatFD
          - href: gfdata.qmd
            text: gfdata
      - section: "Datasets"
        contents:
          - href: airqualitybogota.qmd
            text: AirQualityBogota
          - href: vowels.qmd
            text: Vowels
          - href: cokmexico.qmd
            text: CokMexico
      - section: "Kriging"
        contents:
          - href: kriging.qmd
            text: Kriging
          - href: cokriging.qmd
            text: Cokriging
      - section: "Diseño Óptimo"
        contents:
          - href: optimal_design.qmd
            text: Diseño Óptimo
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/mpbohorquezc/SpatFD-Functional-Geostatistics/tree/main
          - text: Report a Bug
            href: https://github.com/mpbohorquezc/SpatFD-Functional-Geostatistics/issues

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
