---
title: "Clasificación"
format: html
editor: visual
---

## Descripción

Esta función clasifica nuevos datos funcionales basándose en los resultados del PCA de los datos de entrenamiento.

## Uso

```r
classification(data.train.pca, new.basis, k, distance, mcov = NULL)
```

## Argumentos

-   **data.train.pca**: Una lista de resultados de PCA a partir de los datos de entrenamiento.

-   **new.basis**: Objeto de base a partir de los datos de prueba.

-   **k**: Número de vecinos más cercanos a considerar para la clasificación.

-   **distance**: Tipo de distancia a utilizar (por ejemplo, "euclidiana", "mahalanobis").

-   **mcov**: Matrices de covarianza opcionales para la distancia de Mahalanobis.

## Valor

La función devuelve la clase predicha para los nuevos datos.

## Detalles

El proceso de clasificación utiliza los resultados del PCA sobre los datos de entrenamiento para clasificar nuevos puntos de datos. Emplea un algoritmo de k vecinos más cercanos, donde la métrica de distancia puede ser especificada por el usuario.

## Ejemplos

``` r
data(vowels)
#### Crear parámetros y nombres para los datos.
p = 228 ; nelec = 21 ; nvow = 5
names_vowels = c("a","e","i","o","u")
n.basis <- c(14, 13, 12, 13, 11)
s4.gfdata = gfdata(data = vowels, p = p, names = names_vowels, coords = vowels_coords, nbasis = n.basis)

# Crear datos de entrenamiento y prueba
s4.sep = gfd_clasif_data(s4.gfdata, 0.8, seed = 2910)
s4.train = s4.sep$train
s4.test = s4.sep$test

# Clasificación
cla <- classification(data.train.pca = s4.train,
                      new.basis = s4.test[[1]]$data_fd[[1]],
                      k = 4,
                      distance = 'euclidean',
                      mcov = mcov)
```
